name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main, fix-github-pages ]

jobs:
  deploy:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Install additional dependencies
        run: |
          pip install beautifulsoup4 nbformat nbconvert sphinx==5.0.2 gpytorch 'botorch>=0.1.3' jinja2

      - name: Build AEPsych documentation
        run: |
          chmod +x ./scripts/build_docs.sh
          ./scripts/build_docs.sh -b

      - name: Clean up gh-pages branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout --orphan gh-pages
          git reset --hard
          git clean -fdx

      - name: Copy site files
        run: |
          cp -r ./website/build/aepsych/* ./

      - name: Commit and push changes
        run: |
          git add --all
          git commit -m "Deploy updated documentation"
          git push --force --set-upstream origin gh-pages
