name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main, fix-github-pages ]

jobs:
  deploy:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches to allow for gh-pages operations

      # Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install Python dependencies
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      # Install additional dependencies
      - name: Install additional dependencies
        run: |
          pip install beautifulsoup4 nbformat nbconvert sphinx==5.0.2 gpytorch 'botorch>=0.1.3' jinja2

      # Build the AEPsych documentation
      - name: Build AEPsych documentation
        run: |
          chmod +x ./scripts/build_docs.sh
          ./scripts/build_docs.sh -b

      # Debug: Check contents of the build directory
      - name: Check build output
        run: |
          ls -R ./website/build  # Verifying that the site was built correctly


      # Verify if build files are available before copying
      - name: Verify site files exist
        run: |
          if [ ! -d "./website/build/aepsych" ]; then
            echo "Build directory ./website/build/aepsych does not exist. Exiting."
            exit 1
          fi

      # Copy built site files to the root for deployment
      - name: Copy site files
        run: |
          cp -r ./website/build/aepsych/* ./

      # Commit and push changes to gh-pages
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "Deploy updated documentation"
          git push --force --set-upstream origin gh-pages
